- link:
    ~/.config/zsh/.p10k.zsh: configfiles/zsh/p10k.zsh
    ~/.config/zsh/.zshrc-alias: configfiles/zsh/zshrc-alias
    ~/.config/zsh/.zshrc-functions: configfiles/zsh/zshrc-functions
    ~/.zshrc: configfiles/zsh/.zshrc
