#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

[ -f /etc/xprofile  ] && . /etc/xprofile
[ -f ~/.xprofile  ] && . ~/.xprofile

# Run all system xinitrc shell scripts
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# run window manager
#exec i3
