import = [
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
term = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
# family = "hack"
family= "MesloLGS NF"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[[keyboard.bindings]]
chars = "zi\r"
key = "G"
mods = "Control"

[scrolling]
history = 50000

# [window]
# opacity = 0.8
